CXX= mpic++
CXXFLAGS= -O2

all: block unblock barrier

block: block.cpp
	${CXX} ${CXXFLAGS} block.cpp -o block

unblock: unblock.cpp
	${CXX} ${CXXFLAGS} unblock.cpp -o unblock

barrier:barrier.cpp
	${CXX} ${CXXFLAGS} barrier.cpp -o barrier


